import './filter.js';
import './table.js';
import './formButtons.js';
import './image.js';
import './modalDelete.js';
import './modalFilter.js'
import './formValidation.js'
import './title.js'
import './menuHamburguer.js'