import './menu.js';
import './filter.js';
import './mainButton.js';
import './imagesButton.js';
import './editButton.js';
import './broomButton.js';
import './deleteButton.js';
import './saveButton.js';
import './image.js';
